fix (many) shellcheck warnings
bjorn3/rustc_codegen_cranelift pull request #1109
Opened 2020-11-04 15:16 UTC by jakobhellermann

Related issue: #1107 

The first commit fixes the 'machine applicable' shellcheck warnings, the second one fixes some manually.

There are still some warnings left:

```
In build_sysroot/prepare_sysroot_src.sh line 24:
for file in $(ls ../../patches/ | grep -v patcha); do
              ^-- SC2010: Don't use ls | grep. Use a glob or a for loop with a condition to allow non-alphanumeric filenames.
```
I wasn't sure why you were ignoring 'patcha' here. Is this still needed?

```
In scripts/config.sh line 31:
      RUN_WRAPPER='wine'
      ^---------^ SC2034: RUN_WRAPPER appears unused. Verify use (or export if used externally).
```
Was this supposed to be used somewhere?

```
In scripts/rustup.sh line 30:
	cg_clif=$(pwd)
        ^-----^ SC2034: cg_clif appears unused. Verify use (or export if used externally).
```
Same as above.

```
In scripts/tests.sh line 102:
    cat examples/regexdna-input.txt | ../build/cargo.sh run --example shootout-regex-dna | grep -v "Spawned thread" > res.txt
        ^-------------------------^ SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
```
I think not using cat here makes readability worse.

2020-11-04 15:28 UTC, bjorn3 requested changes
Thanks!

> I wasn't sure why you were ignoring 'patcha' here. Is this still needed?

It allowed for quick disabling of specific patches by renaming them. I haven't used it in months, but it could be useful to keep.

> Was this supposed to be used somewhere?

`config.sh` is sourced by several files. `RUN_WRAPPER` is used by `tests.sh`.

> I think not using cat here makes readability worse.

I agree

2020-11-04 15:28 UTC, bjorn3 commented on scripts/cargo.sh
> +cargo "+${TOOLCHAIN}" rustc "$@" -- --jit
The old behavior is deliberate. Separate arguments to `cargo.sh` should be passed as separate arguments to cargo.

2020-11-04 15:28 UTC, bjorn3 commented on scripts/config.sh
> +#!/bin/bash
This file should never be executed, only sourced. Please remove this line and revert permissions back.

2020-11-04 15:28 UTC, bjorn3 commented on test.sh
> +./build.sh --without-sysroot "$@"
Same re separate arguments.

2020-11-04 15:28 UTC, bjorn3 commented on scripts/config.sh
> +export LD_LIBRARY_PATH
I slightly prefer the old version.

2020-11-05 09:16 UTC, jakobhellermann commented on scripts/cargo.sh
> +cargo "+${TOOLCHAIN}" rustc "$@" -- --jit
Actually I think this is correct: https://stackoverflow.com/a/3990540

"$@" expands to "$1" "$2" "$3".

The difference between `$@` and `"$@"` occurs when doing something like `./script "*" b c`, where the quoted variant will pass the * and the unquoted one will expand it.

2020-11-05 09:17 UTC, jakobhellermann commented on scripts/config.sh
> +#!/bin/bash
same as above

2020-11-05 09:17 UTC, jakobhellermann commented on scripts/config.sh
> +export LD_LIBRARY_PATH
I think the motivation was that if `rustc --print sysroot` fails, ` set -e` will not catch it inside an export, but I can change it.

2020-11-05 09:19 UTC, jakobhellermann commented on scripts/config.sh
> +#!/bin/bash
Done :+1:

2020-11-05 09:23 UTC, bjorn3 commented on scripts/cargo.sh
> +cargo "+${TOOLCHAIN}" rustc "$@" -- --jit
Didn't know that.

2020-11-05 09:24 UTC, bjorn3 approved these changes
Thanks!

2020-11-05 11:12 UTC, merged