Move test script to y.rs
bjorn3/rustc_codegen_cranelift pull request #1252
Opened 2022-07-30 09:57 UTC by afonso360

👋  Hey,

This PR moves the tests scripts over to a subcommand on `y.rs`.

We now use `config.txt` to check which tests we should run. This allows the user to edit the file while the testsuite is running to skip running some tests.

Another change is that instead of passing `no_sysroot`/`base_sysroot`/`extended_sysroot` as a test argument, we also check those as keys in `config.txt`. Let me know if this is a feature that we want to keep as it was before @bjorn3.

cc: #1176

2022-07-30 10:42 UTC, bjorn3 requested changes
Thanks a lot!

> Another change is that instead of passing no_sysroot/base_sysroot/extended_sysroot as a test argument, we also check those as keys in config.txt. Let me know if this is a feature that we want to keep as it was before @bjorn3.

I don't recall every having invoked scripts/tests.sh directly.

2022-07-30 10:42 UTC, bjorn3 commented on build_system/mod.rs
> +        // TODO: Should we also build_backend here?
Yes. It should build the backend first. Could you turn this `if` into a match and move build_backend before it?

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +                    .filter(|line| !line.contains("Spawned thread"))
Not sure filtering "Spawned thread" is still necessary. I think not.

2022-07-30 10:42 UTC, bjorn3 commented on build_system/build_sysroot.rs
> +        let wrapper_name = if cfg!(windows) {
This should check the target. There is basic support for cross-compiling in the build system. Or better it should use `get_file_name` too. By the way `get_file_name` needs a target argument I think.

2022-07-30 10:42 UTC, bjorn3 commented on build_system/build_backend.rs
> -    Path::new("target").join(host_triple).join(channel)
Could you revert this change?

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +        runner.run_rustc(["example/mini_core.rs", "--crate-name", "mini_core", "--crate-type", "lib,dylib", "--target", &runner.target_triple]);
These now all miss the `[BUILD] mini_core` output lines, right?

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +    Ok(fs::remove_dir_all(out_dir)?)
Could you inline this function?

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +        let env_run_wrapper = env::var("RUN_WRAPPER").ok();
`RUN_WRAPPER` is not a public env var. It is always overwritten and it probably shouldn't even have been exported as env var. Could you avoid checking it?

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +    rust_flags: Vec<String>,
I think `rust_flags` should be represented as `String`, as this is how it will be passed to cargo anyway.

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +            let is_jit_test = config.contains("jit");
I think this should check that the tag is an exact match to `"jit"`.

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +        }
This should use `get_file_name`.

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +        }
Same

2022-07-30 10:42 UTC, bjorn3 commented on build_system/tests.rs
> +                if output != expected {
Somewhere this is going wrong on CI:

```
--- res.txt	2022-07-30 10:22:41.404652369 +0000
+++ examples/regexdna-output.txt	2019-07-21 03:01:44.000000000 +0000
@@ -1,13 +1,13 @@
-agggtaaa|tttaccct 0
-[cgt]gggtaaa|tttaccc[acg] 3
-a[act]ggtaaa|tttacc[agt]t 9
-ag[act]gtaaa|tttac[agt]ct 8
-agg[act]taaa|ttta[agt]cct 10
-aggg[acg]aaa|ttt[cgt]ccct 3
-agggt[cgt]aa|tt[acg]accct 4
-agggta[cgt]a|t[acg]taccct 3
-agggtaa[cgt]|[acg]ttaccct 5
-
-101745
-100000
-133640
+agggtaaa|tttaccct 0
+[cgt]gggtaaa|tttaccc[acg] 3
+a[act]ggtaaa|tttacc[agt]t 9
+ag[act]gtaaa|tttac[agt]ct 8
+agg[act]taaa|ttta[agt]cct 10
+aggg[acg]aaa|ttt[cgt]ccct 3
+agggt[cgt]aa|tt[acg]accct 4
+agggta[cgt]a|t[acg]taccct 3
+agggtaa[cgt]|[acg]ttaccct 5
+
+101745
+100000
+133640
```

2022-07-30 10:42 UTC, bjorn3 commented on .github/workflows/main.yml
> +        ./y.rs test
I think the job running on windows could now run tests too.

2022-07-30 11:17 UTC, afonso360 commented on build_system/tests.rs
> +                    .filter(|line| !line.contains("Spawned thread"))
I didn't see any of those in the output, ill remove this.

2022-07-30 11:21 UTC, afonso360 commented on build_system/tests.rs
> +        runner.run_rustc(["example/mini_core.rs", "--crate-name", "mini_core", "--crate-type", "lib,dylib", "--target", &runner.target_triple]);
We emit those lines from the `TestCase` name. The tag gets upper cased, and the rest of the line is the test name.

It gives a similar output, although not exactly equal.

2022-07-30 21:33 UTC, afonso360 commented on build_system/rustc_info.rs
> +pub(crate) fn get_file_name(crate_name: &str, crate_type: &str, target: &str) -> String {
Turns out we always need the host triple when calling this. Would you like me to revert this change?

2022-07-30 21:35 UTC, afonso360 commented on build_system/tests.rs
> +        cmd.args(self.rust_flags.split_whitespace());
I really don't know what's going on here. If we don't pass the flags manually as args they never get processed. Despite us explicitly passing it in the env below.

Any ideas?

2022-07-30 21:38 UTC, afonso360 commented
Sorry for the slightly messy PR and thanks for reviewing! I'm still learning my way around cg_clif.

It looks like the windows build is broken, is there a way to mark it as non blocking for CI?

2022-07-30 21:47 UTC, bjorn3 commented
I think reverting back to only running builds is best until all tests are fixed. Otherwise no windows artifacts will be released anymore.

2022-07-30 21:49 UTC, bjorn3 commented on build_system/rustc_info.rs
> +pub(crate) fn get_file_name(crate_name: &str, crate_type: &str, target: &str) -> String {
It would be necessary when cross compiling the codegen backend and not just the sysroot, but given that cross compiling doesn't work due to rustc using proc macros (which are not compiled for the build triple), I think it is fine to revert this back.

2022-07-30 21:51 UTC, bjorn3 commented on build_system/tests.rs
> +        cmd.args(self.rust_flags.split_whitespace());
RUSTFLAGS is only recognized by cargo and not by rustc.

2022-07-31 10:21 UTC, bjorn3 commented
Thanks a lot! I pushed a commit to rustfmt the build system.

2022-07-31 10:22 UTC, merged